FROM fedora:42@sha256:16ca3e34a9545583551589e71882f1f27cbce3c2f1fc6210c932d22a6931b73b

ARG MESA_VERSION="24.1.2-101"

USER 0

# Install the patched mesa-krunkit drivers
RUN dnf -y install dnf-plugins-core && \
    dnf -y copr enable slp/mesa-krunkit epel-9-aarch64 && \
    dnf -y install \
        mesa-vulkan-drivers-$MESA_VERSION.el9.aarch64 && \
    dnf clean all
