{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ (printf "%s-webui" (include "snapgen.fullname" .)) }}
  labels:
    {{- include "snapgen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "snapgen.selectorLabelsUI" . | nindent 4 }}
{{- end}}
