name: pre-release

on:
  workflow_dispatch: 
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  pre-release:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e
        with:
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443
            fulcio.sigstore.dev:443
            ghcr.io:443
            github.com:443
            *.githubusercontent.com:443
            pkg-containers.githubusercontent.com:443
            production.cloudflare.docker.com:443
            proxy.golang.org:443
            registry-1.docker.io:443
            rekor.sigstore.dev:443
            storage.googleapis.com:443
            tuf-repo-cdn.sigstore.dev:443
            sum.golang.org:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Install Cosign
        uses: sigstore/cosign-installer@c56c2d3e59e4281cc41dea2217323ba5694b171e

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca

      - name: Login to GHCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set LDFLAGS
        run: |
          set -x
          GIT_COMMIT=$(git rev-list --abbrev-commit --tags --max-count=1 || echo "")
          GIT_TAG=$(git describe --abbrev=0 --tags ${GIT_COMMIT} 2>/dev/null || echo "")
          echo LDFLAGS="-X github.com/sozercan/snapgen/pkg/version.Version=${GIT_TAG}" >> $GITHUB_ENV

      - name: Build and push
        run: |
          echo "🟡 Build and push step skipped. TODO: Re-enable once registry permissions are fixed."

      - name: Sign image (temporarily disabled)
        run: echo "🟡 Signing skipped. No image built."
      
      - name: Verify image signature (temporarily disabled)
        run: echo "🟡 Verification skipped. No image built."

