name: docker-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v4

      - name: cleanup disk space
        run: |
          df -H
          docker system prune -f -a --volumes
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -H

      - name: create buildx builder
        run: docker buildx create --use --name builder --bootstrap
      - uses: crazy-max/ghaction-github-runtime@v3

      - name: build snapgen
        run: docker buildx build . -t sozercan/snapgen:test --load --cache-from=type=gha,scope=snapgen --cache-to=type=gha,scope=snapgen,mode=max

      - name: build test model
        run: docker buildx build . -t sozercan/testmodel:test -f test/snapgenfile.yaml --load --cache-from=type=gha,scope=testmodel --cache-to=type=gha,scope=testmodel,mode=max

      - name: list images
        run: docker images

      - name: run test model
        run: docker run -d -p 8080:8080 sozercan/testmodel:test

      - name: install e2e dependencies
        run: make test-e2e-dependencies

      - name: run bats test
        run: make test-e2e
