name: helm-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'website/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'website/**'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be 
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e 
        with:
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443
            huggingface.co:443
            *.huggingface.co:443
            *.hf.co:443
            cdn.dl.k8s.io:443
            dl.k8s.io:443
            download.docker.com:443
            gcr.io:443
            github.com:443
            *.githubusercontent.com:443
            production.cloudflare.docker.com:443
            proxy.golang.org:443
            registry-1.docker.io:443
            storage.googleapis.com:443
            *.ubuntu.com:80
            developer.download.nvidia.com:443
            get.helm.sh:443
            *.blob.core.windows.net:443
            *.azureedge.net:443
            registry.k8s.io:443
            *.pkg.dev:443
            *.amazonaws.com:443
            dl-cdn.alpinelinux.org:443
            ghcr.io:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 
      
      - uses: crazy-max/ghaction-setup-docker@370a7dad4b8ce8dbf00f9363e1652e5074dd6abe 
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - uses: crazy-max/ghaction-github-runtime@b3a9207c0e1ef41f4cf215303c976869d0c2c1c4 

      - name: build snapgen
        run: |
          docker buildx build . -t snapgen:test \
            --load --provenance=false --progress plain \
            --cache-from=type=gha,scope=snapgen-amd64 \
            --cache-to=type=gha,scope=snapgen-amd64,mode=max

      - name: build test model
        run: |
          docker buildx build . -t testmodel:test \
            -f test/snapgenfile-llama.yaml \
            --load --provenance=false --progress plain \
            --cache-from=type=gha,scope=testmodel-amd64 \
            --cache-to=type=gha,scope=testmodel-amd64,mode=max

      - name: list images
        run: docker images

      - name: install e2e dependencies
        run: make test-e2e-dependencies

      - name: create kind cluster
        run: kind create cluster --wait 5m

      - name: load test model image into kind cluster
        run: kind load docker-image testmodel:test

      - name: deploy test model
        run: |
          helm install charts/snapgen --wait --debug \
            --name-template snapgen --namespace snapgen --create-namespace \
            --set image.repository=testmodel \
            --set image.tag=test \
            --set image.pullPolicy=Never
          kubectl port-forward -n snapgen service/snapgen 8080:8080 &

      - name: run test (temporarily disabled)
        run: |
          echo "🟡 Test temporarily disabled. TODO: Re-enable once the endpoint is working properly."

      - name: save logs
        if: always()
        run: |
          echo "KIND_LOGS_PATH=$(kind export logs)" >> $GITHUB_ENV

      - name: publish logs
        if: always()
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 
        with:
          name: kind-logs
          path: $KIND_LOGS_PATH
